/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32 */

#ifndef _Included_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
#define _Included_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
 * Method:    add
 * Signature: (Ljmtp/PropVariant;)V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32_clear
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
 * Method:    count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32_count
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
 * Method:    getAt
 * Signature: (J)Ljmtp/PropVariant;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32_getAt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32
 * Method:    removeAt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDevicePropVariantCollectionImplWin32_removeAt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
