/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDeviceObjectInputStream */

#ifndef _Included_jmtp_implWin32_PortableDeviceObjectInputStream
#define _Included_jmtp_implWin32_PortableDeviceObjectInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef jmtp_implWin32_PortableDeviceObjectInputStream_MAX_SKIP_BUFFER_SIZE
#define jmtp_implWin32_PortableDeviceObjectInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     jmtp_implWin32_PortableDeviceObjectInputStream
 * Method:    readDataToBuffer
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_jmtp_implWin32_PortableDeviceObjectInputStream_readDataToBuffer
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jmtp_implWin32_PortableDeviceObjectInputStream
 * Method:    closeIStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceObjectInputStream_closeIStream
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
