/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDeviceResourcesImplWin32 */

#ifndef _Included_jmtp_implWin32_PortableDeviceResourcesImplWin32
#define _Included_jmtp_implWin32_PortableDeviceResourcesImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_implWin32_PortableDeviceResourcesImplWin32
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceResourcesImplWin32_cancel
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceResourcesImplWin32
 * Method:    delete
 * Signature: (Ljava/lang/String;Ljmtp/implWin32/PortableDeviceKeyCollectionImplWin32;)V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceResourcesImplWin32_delete
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceResourcesImplWin32
 * Method:    getSupportedResources
 * Signature: (Ljava/lang/String;)Ljmtp/implWin32/PortableDeviceKeyCollectionImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDeviceResourcesImplWin32_getSupportedResources
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_implWin32_PortableDeviceResourcesImplWin32
 * Method:    getResourceAttributes
 * Signature: (Ljava/lang/String;Ljmtp/PropertyKey;)Ljmtp/implWin32/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDeviceResourcesImplWin32_getResourceAttributes
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceResourcesImplWin32
 * Method:    getInputStream
 * Signature: (Ljava/lang/String;Ljmtp/PropertyKey;)Ljmtp/implWin32/PortableDeviceObjectInputStream;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDeviceResourcesImplWin32_getInputStream
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceResourcesImplWin32
 * Method:    getOutputStream
 * Signature: (Ljava/lang/String;Ljmtp/PropertyKey;)Ljmtp/implWin32/PortableDeviceObjectOutputStream;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDeviceResourcesImplWin32_getOutputStream
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
