/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDeviceContentImplWin32 */

#ifndef _Included_jmtp_implWin32_PortableDeviceContentImplWin32
#define _Included_jmtp_implWin32_PortableDeviceContentImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    createObjectWithPropertiesAndData
 * Signature: (Ljmtp/implWin32/PortableDeviceValuesImplWin32;Ljava/io/InputStream;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_createObjectWithPropertiesAndData
  (JNIEnv *, jobject, jobject, jobject, jlong);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    updateObjectWithPropertiesAndData
 * Signature: (Ljava/lang/String;Ljmtp/implWin32/PortableDeviceValuesImplWin32;Ljava/io/InputStream;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_updateObjectWithPropertiesAndData
  (JNIEnv *, jobject, jstring, jobject, jobject, jlong);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    createObjectWithPropertiesOnly
 * Signature: (Ljmtp/implWin32/PortableDeviceValuesImplWin32;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_createObjectWithPropertiesOnly
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    delete
 * Signature: (ILjmtp/implWin32/PortableDevicePropVariantCollectionImplWin32;)V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_delete
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    listChildObjects
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_listChildObjects
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    getProperties
 * Signature: ()Ljmtp/implWin32/PortableDevicePropertiesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    getObjectIDsFromPersistentUniqueIDs
 * Signature: (Ljmtp/implWin32/PortableDevicePropVariantCollectionImplWin32;)Ljmtp/implWin32/PortableDevicePropVariantCollectionImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_getObjectIDsFromPersistentUniqueIDs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceContentImplWin32
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceContentImplWin32_cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
