/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDevicePropertiesImplWin32 */

#ifndef _Included_jmtp_implWin32_PortableDevicePropertiesImplWin32
#define _Included_jmtp_implWin32_PortableDevicePropertiesImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_implWin32_PortableDevicePropertiesImplWin32
 * Method:    getPropertyAttributes
 * Signature: (Ljava/lang/String;Ljmtp/PropertyKey;)Ljmtp/implWin32/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDevicePropertiesImplWin32_getPropertyAttributes
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_implWin32_PortableDevicePropertiesImplWin32
 * Method:    getSupprtedProperties
 * Signature: (Ljava/lang/String;)Ljmtp/implWin32/PortableDeviceKeyCollectionImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDevicePropertiesImplWin32_getSupprtedProperties
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_implWin32_PortableDevicePropertiesImplWin32
 * Method:    getValues
 * Signature: (Ljava/lang/String;Ljmtp/implWin32/PortableDeviceKeyCollectionImplWin32;)Ljmtp/implWin32/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDevicePropertiesImplWin32_getValues
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_implWin32_PortableDevicePropertiesImplWin32
 * Method:    setValues
 * Signature: (Ljava/lang/String;Ljmtp/implWin32/PortableDeviceValuesImplWin32;)Ljmtp/implWin32/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_implWin32_PortableDevicePropertiesImplWin32_setValues
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
