/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDeviceObjectOutputStream */

#ifndef _Included_jmtp_implWin32_PortableDeviceObjectOutputStream
#define _Included_jmtp_implWin32_PortableDeviceObjectOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_implWin32_PortableDeviceObjectOutputStream
 * Method:    writeDataIStream
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_jmtp_implWin32_PortableDeviceObjectOutputStream_writeDataIStream
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jmtp_implWin32_PortableDeviceObjectOutputStream
 * Method:    closeIStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceObjectOutputStream_closeIStream
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
