/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDeviceObjectImplWin32 */

#ifndef _Included_jmtp_implWin32_PortableDeviceObjectImplWin32
#define _Included_jmtp_implWin32_PortableDeviceObjectImplWin32
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
