/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PropVariant */

#ifndef _Included_jmtp_PropVariant
#define _Included_jmtp_PropVariant
#ifdef __cplusplus
extern "C" {
#endif
#undef jmtp_PropVariant_VT_EMPTY
#define jmtp_PropVariant_VT_EMPTY 0L
#undef jmtp_PropVariant_VT_NULL
#define jmtp_PropVariant_VT_NULL 1L
#undef jmtp_PropVariant_VT_BOOL
#define jmtp_PropVariant_VT_BOOL 11L
#undef jmtp_PropVariant_VT_LPSTR
#define jmtp_PropVariant_VT_LPSTR 30L
#undef jmtp_PropVariant_VT_LPWSTR
#define jmtp_PropVariant_VT_LPWSTR 31L
#undef jmtp_PropVariant_EPOCH_DIFF
#define jmtp_PropVariant_EPOCH_DIFF 11644473600000i64
#ifdef __cplusplus
}
#endif
#endif
