/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_ResourceAttributeWin32Impl */

#ifndef _Included_jmtp_implWin32_ResourceAttributeWin32Impl
#define _Included_jmtp_implWin32_ResourceAttributeWin32Impl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
