/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_implWin32_PortableDeviceManagerImplWin32 */

#ifndef _Included_jmtp_implWin32_PortableDeviceManagerImplWin32
#define _Included_jmtp_implWin32_PortableDeviceManagerImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_implWin32_PortableDeviceManagerImplWin32
 * Method:    getDevicesImpl
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jmtp_implWin32_PortableDeviceManagerImplWin32_getDevicesImpl
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_implWin32_PortableDeviceManagerImplWin32
 * Method:    refreshDeviceListImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_implWin32_PortableDeviceManagerImplWin32_refreshDeviceListImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
